let proyectos = [
  {
    id: 0,
    featured: true,
    title: "Bodhiria",
    artist: "Judeline",
    country: ["spain"],
    type: "album",
    genre: "avant-pop",
    status: "released",
    releaseDate: "2024-10-24",
    coverImage: "img/covers/bodhiria.jpg",
    artistImage: "img/artists/judeline.jpg",
    tracks: ["bodhitale", "INRI", "angelA", "mangata", "BRUJERIA!", "luna roja", "JOROPO", "4esquinitas", "4 angelitos", "Heavenly", "zarcillos de plata", "Es Dios bueno o sólo es poderoso"],
    totalTracks: 12,
    popularity: 63,
    spotifyUrl: "https://open.spotify.com/album/3fVXh36WypsZR2JGathvkq",
    description: "A blend of electronic music, alternative pop, and Spanish musical traditions that creates a world that feels both intimate and expansive. Atmospheric production, layered vocals, and emotionally charged songwriting explore themes of desire, spirituality, memory, and personal transformation while maintaining a strong and distinctive artistic identity.",
    tourStart: "2025-10-03",
    tourEnd: "2026-05-01"
  },
  {
    id: 1,
    featured: true,
    title: "DAISY",
    artist: "rusowsky",
    country: ["spain"],
    type: "album",
    genre: "avant-pop",
    status: "released",
    releaseDate: "2025-05-23",
    coverImage: "img/covers/daisy.jpg",
    artistImage: "img/artists/rusowsky.jpg",
    tracks: ["KINKI FÍGARO", "Johnny Glamour", "SOPHIA", "BBY ROMEO", "pink + pink", "ALTAGAMA", "4 Daisy", "malibU", "LIAR?", "(ecco)", "sukkKK!!", "project tu culo", "99%"],
    totalTracks: 13,
    popularity: 58,
    spotifyUrl: "https://open.spotify.com/album/0o1RGF3A02UN1aVAX1SLuQ",
    description: "A colorful and unpredictable collection of songs where experimental pop meets electronic production and digital-era sensibilities. Constant shifts in mood, texture, and structure create a playful yet emotional experience centered on connection, identity, longing, and the complexities of modern relationships.",
    tourStart: "2025-07-03",
    tourEnd: "2026-05-02"
  },
  {
    id: 2,
    featured: true,
    title: "Tristán, Ahora Con Reloj",
    artist: "TRISTÁN!",
    country: ["spain"],
    type: "album",
    genre: "indie pop",
    status: "released",
    releaseDate: "2025-10-10",
    coverImage: "img/covers/tristan-ahora-con-reloj.jpg",
    artistImage: "img/artists/tristan.jpg",
    tracks: ["Mapamundi", "Capitán Cocodrilo", "Life Is A Movie", "Tutta La Notte (feat. Calcutta)", "Verónica", "Kung Fu Beat", "#7/ Trashumancia", "Voyage", "Estoy Amándote Tan Fuerte", "Baby, Don’t Miss It", "Ártico", "Green Love"],
    totalTracks: 12,
    popularity: 27,
    spotifyUrl: "https://open.spotify.com/album/7oDxt14IyAbiLAxlCMLHEe",
    description: "A nostalgic journey filled with cinematic imagery, romantic storytelling, and adventurous pop songwriting. Bright melodies and imaginative arrangements blur the line between fantasy and reality, creating a world where memories, dreams, and everyday moments coexist in vibrant and unexpected ways.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 3,
    featured: true,
    title: "VERANO SAUDADE",
    artist: "Judeline",
    country: ["spain"],
    type: "EP",
    genre: "alternative pop",
    status: "released",
    releaseDate: "2025-12-11",
    coverImage: "img/covers/verano-saudade.jpg",
    artistImage: "img/artists/judeline.jpg",
    tracks: ["mi breve juventud", "com você", "tiempo pasa", "PIKI", "TÚ ET MOI"],
    totalTracks: 5,
    popularity: 54,
    spotifyUrl: "https://open.spotify.com/album/4NiMrAqxTakrdJi0DNGwFd",
    description: "A warm and reflective project inspired by fading summers, fleeting relationships, and the emotional weight of nostalgia. Drawing from Iberian and Latin American influences, it balances intimacy and melancholy through delicate melodies, organic textures, and an atmosphere that feels timeless.",
    tourStart: "2025-06-07",
    tourEnd: "2026-05-01"
  },
  {
    id: 4,
    featured: false,
    title: "Si Abro Los Ojos No Es Real",
    artist: "Amaia",
    country: ["spain"],
    type: "album",
    genre: "indie pop",
    status: "released",
    releaseDate: "2025-01-30",
    coverImage: "img/covers/si-abro-los-ojos-no-es-real.jpg",
    artistImage: "img/artists/amaia.jpg",
    tracks: ["Visión", "Tocotó", "Nanai", "M.A.P.S.", "Auxiliar", "Magia En Benidorm", "Tengo Un Pensamiento", "C’est La Vie", "Giratutto", "Despedida", "Fantasma", "Ya Está"],
    totalTracks: 12,
    popularity: 57,
    spotifyUrl: "https://open.spotify.com/album/5hdd9BcMltcCZpAgcjXtCT",
    description: "An elegant exploration of dreams, imagination, and emotional vulnerability. Detailed arrangements and subtle production transform ordinary thoughts into vivid sonic landscapes, creating an immersive experience that constantly shifts between reality, memory, and fantasy.",
    tourStart: "2025-06-07",
    tourEnd: "2026-05-31"
  },
  {
    id: 5,
    featured: true,
    title: "epistolares+",
    artist: "AKRIILA",
    type: "album",
    genre: "hyperpop",
    country: ["chile"],
    status: "released",
    releaseDate: "2025-05-15",
    coverImage: "img/covers/epistolares.jpg",
    artistImage: "img/artists/akriila.jpg",
    tracks: ["debut", "epitafio", "worldw1de (feat. Princesa Alba)", "NANA フリーク版", "www.hotxulito.com", "POPPER!", "mucho, poquito, nada", "superficial", "teoría del tiempo", "para siempre(｡>﹏<)", "lunes feriadooOoOO", "carta a mi papá", "post", "mal comunicada", "sola", "paranormal", "002 (durísimo)", "+ q ayer"],
    totalTracks: 18,
    popularity: 43,
    spotifyUrl: "https://open.spotify.com/album/7vS5TDQ9oUakyWAtBqlldL",
    description: "An emotionally intense project where hyperpop, electronic experimentation, and deeply personal storytelling come together. Through confessional lyrics and constantly evolving production, it explores identity, relationships, loneliness, and self-discovery with both vulnerability and confidence.",
    tourStart: "2025-07-02",
    tourEnd: "2026-05-01"
  },
  {
    id: 6,
    featured: false,
    title: "El Templo del Pop",
    artist: "Miranda!",
    country: ["argentina"],
    type: "album",
    genre: "synthpop",
    status: "released",
    releaseDate: "2008-04-01",
    coverImage: "img/covers/el-templo-del-pop.jpg",
    artistImage: "img/artists/miranda.jpg",
    tracks: ["Perfecta", "Chicas", "Enamorada", "Don", "Yo Te Diré", "Traición", "Bailarina", "Prisionero", "Imán", "Hola", "El Profe", "Romix", "Otra Vez (Vivo)", "Mi Propia Vida", "Uno los Dos", "Tu Juego", "Vete de Aquí", "Navidad", "Quereme… Tengo Frío", "Miranda Mix (Oíd Mortales Mix)"],
    totalTracks: 20,
    popularity: 70,
    spotifyUrl: "https://open.spotify.com/album/0KzE84u9io1eWxWSs9SmSY",
    description: "A celebration of infectious melodies, unforgettable choruses, and the vibrant energy that defines modern Latin pop. The collection captures the spirit of an era while showcasing songs that remain instantly recognizable and emotionally resonant years after their release.",
    tourStart: "2025-06-27",
    tourEnd: "2026-05-29"
  },
  {
    id: 7,
    featured: false,
    title: "Fancy That",
    artist: "PinkPantheress",
    country: ["united kingdom", "england"],
    type: "album",
    genre: "uk garage",
    status: "released",
    releaseDate: "2025-05-09",
    coverImage: "img/covers/fancy-that.jpg",
    artistImage: "img/artists/pinkpantheress.jpg",
    tracks: ["Illegal", "Girl Like Me", "Tonight", "Stars", "Intermission", "Noises", "Nice to Know You", "Stateside", "Romeo"],
    totalTracks: 9,
    popularity: 70,
    spotifyUrl: "https://open.spotify.com/album/3o81FH5FTYVtoBQOZr3T7y",
    description: "A concise yet dynamic project driven by catchy hooks, UK garage influences, and sleek electronic production. Its playful energy and contemporary sound transform everyday emotions into songs that feel both intimate and effortlessly addictive.",
    tourStart: "2025-06-15",
    tourEnd: "2026-06-02"
  },
  {
    id: 8,
    featured: true,
    title: "Fancy Some More?",
    artist: "PinkPantheress",
    country: ["united kingdom", "england"],
    type: "album",
    genre: "uk garage",
    status: "released",
    releaseDate: "2025-10-10",
    coverImage: "img/covers/fancy-some-more.jpg",
    artistImage: "img/artists/pinkpantheress.jpg",
    tracks: ["Illegal + Anitta", "Illegal + SEVENTEEN", "Girl Like Me + Oklou", "Tonight + JADE", "Stars + Yves", "Noises + JT", "Nice to Know You + Sugababes", "Stateside + Kylie Minogue", "Stateside + Bladee", "Stateside + Zara Larsson", "Romeo + Ravyn Lenae", "Romeo + Rachel Chinouriri", "Illegal + Nia Archives", "Girl Like Me + Kaytranada", "Tonight + Basement Jaxx", "Tonight + Joe Goddard", "Stars + DJ Caio Prince + Adame DJ", "Noises + Mochakk", "Nice to Know You + Loukeman + Leod", "Nice to Know You + Sega Bodega", "Stateside + Groove Armada", "Romeo + KILIMANJARO", "Illegal", "Girl Like Me", "Tonight", "Stars", "Intermission", "Noises", "Nice to Know You", "Stateside", "Romeo"],
    totalTracks: 31,
    popularity: 68,
    spotifyUrl: "https://open.spotify.com/album/12Lig9oAX9nvpWHft5cHgF",
    description: "An expanded version of an already vibrant musical universe, offering new perspectives through collaborations, alternate versions, and additional material. The result is a broader listening experience that preserves the original project's charm, energy, and emotional immediacy",
    tourStart: "2025-06-15",
    tourEnd: "2026-06-02"
  },
  {
    id: 9,
    featured: false,
    title: "Canciones en Mi",
    artist: "pablopablo",
    country: ["spain", "uruguay"],
    type: "album",
    genre: "singer-songwriter",
    status: "released",
    releaseDate: "2025-05-23",
    coverImage: "img/covers/canciones-en-mi.jpg",
    artistImage: "img/artists/pablopablo.jpg",
    tracks: ["Canciones En Mi", "Dónde Estás!", "Todavía", "Eso Que Tú Llamas Amor", "De Vez En Cuando", "De Ti", "Vida Nueva", "Ojos De Ajonjolí", "Será X Mí", "Tú Te Dabas Cuenta?", "Siempre Te Quiero A Veces", "Las Tuyas"],
    totalTracks: 12,
    popularity: 35,
    spotifyUrl: "https://open.spotify.com/album/4l7m9k9na3sm2sR3BYSTsE",
    description: "An introspective body of work where singer-songwriter traditions meet modern production and subtle experimentation. Themes of memory, personal relationships, and self-reflection run throughout the project, creating an atmosphere that feels deeply personal while remaining universally relatable.",
    tourStart: "2025-06-28",
    tourEnd: "2026-05-09"
  },
  {
    id: 10,
    featured: true,
    title: "Contigo",
    artist: "pablopablo",
    country: ["spain", "uruguay"],
    type: "single",
    genre: "singer-songwriter",
    status: "released",
    releaseDate: "2025-10-15",
    coverImage: "img/covers/contigo.jpg",
    artistImage: "img/artists/pablopablo.jpg",
    tracks: ["Contigo"],
    totalTracks: 1,
    popularity: 30,
    spotifyUrl: "https://open.spotify.com/album/4Yl8mtPufYDfj9n4FWgN9C",
    description: "An intimate song built around vulnerability and emotional closeness, where silence and subtle details carry as much weight as the melody itself. Its minimalist production allows every lyric to take center stage, exploring themes of love, dependence, and genuine human connection.",
    tourStart: "2025-06-28",
    tourEnd: "2026-05-09"
  },
  {
    id: 11,
    featured: false,
    title: "Ángel",
    artist: "IRINA",
    country: ["uruguay", "argentina"],
    type: "single",
    genre: "dream pop",
    status: "released",
    releaseDate: "2025-04-10",
    coverImage: "img/covers/angel.jpg",
    artistImage: "img/artists/irina.jpg",
    tracks: ["Ángel"],
    totalTracks: 1,
    popularity: 25,
    spotifyUrl: "https://open.spotify.com/album/6Ebi8scjYG4d35uB6FAcde",
    description: "A delicate and emotionally charged piece that blends pop sensibilities with an ethereal and reflective atmosphere. Through restrained production and heartfelt delivery, the song explores idealization, fragility, and the lasting impact certain relationships leave behind.",
    tourStart: "2025-06-06",
    tourEnd: "2026-05-22"
  },
  {
    id: 12,
    featured: true,
    title: "MOTOMAMI",
    artist: "ROSALÍA",
    country: ["spain"],
    type: "album",
    genre: "avant-pop",
    status: "released",
    releaseDate: "2022-03-18",
    coverImage: "img/covers/motomami.jpg",
    artistImage: "img/artists/rosalia.jpg",
    tracks: ["SAOKO", "CANDY", "LA FAMA", "BULERÍAS", "CHICKEN TERIYAKI", "HENTAI", "BIZCOCHITO", "G3 N15", "MOTOMAMI", "DIABLO", "DELIRIO DE GRANDEZA", "CUUUUuuuuuute", "COMO UN G", "Abcdefg", "LA COMBI VERSACE", "SAKURA"],
    totalTracks: 16,
    popularity: 95,
    spotifyUrl: "https://open.spotify.com/album/6jbtHi5R0jMXoliU2OS0lo",
    description: "A fearless project that constantly challenges expectations by combining flamenco, reggaeton, electronic music, ballads, and experimental sounds into a single artistic statement. Moving between confidence and vulnerability, it explores identity, fame, desire, ambition, and creative freedom through bold and innovative production.",
    tourStart: "2026-03-15",
    tourEnd: "2026-10-05"
  },
  {
    id: 13,
    featured: false,
    title: ".mp3",
    artist: "Emilia",
    country: ["argentina"],
    type: "album",
    genre: "pop",
    status: "released",
    releaseDate: "2023-11-03",
    coverImage: "img/covers/mp3.jpg",
    artistImage: "img/artists/emilia.jpg",
    tracks: ["Facts.mp3", "Jagger.mp3", "JET_Set.mp3", "IConic.mp3", "La_Original.mp3", "GTA.mp3", "Exclusive.mp3", "No_Se_Ve.mp3", "24_Hs.mp3", "Muñecos.mp3", "Ojitos_Verdes.mp3", "A_1000_Km.mp3", "Guerrero.mp3"],
    totalTracks: 13,
    popularity: 90,
    spotifyUrl: "https://open.spotify.com/album/2qo8j9yZIsx66yDuUho2jp",
    description: "A celebration of pop inspired by early-2000s digital culture and aesthetics. Danceable rhythms, memorable melodies, and polished production come together in a collection of songs that explore love, confidence, fun, and self-discovery through a modern and energetic lens.",
    tourStart: "2025-06-12",
    tourEnd: "2025-11-23"
  },
  {
    id: 14,
    featured: true,
    title: "un mechón de pelo",
    artist: "TINI",
    country: ["argentina"],
    type: "album",
    genre: "pop",
    status: "released",
    releaseDate: "2024-04-11",
    coverImage: "img/covers/un-mechon-de-pelo.jpg",
    artistImage: "img/artists/tini.jpg",
    tracks: ["pa", "posta", "miedo", "ni de ti", "ángel", "buenos aires", "tinta 90", "ellas", "bien", "me voy"],
    totalTracks: 10,
    popularity: 90,
    spotifyUrl: "https://open.spotify.com/album/3wOG84RkmoSoeN3LKkxXga",
    description: "A deeply personal project centered on family bonds, emotional growth, and transformative life experiences. Moments of vulnerability and resilience coexist throughout the record, creating a narrative that reflects on memory, loss, anxiety, healing, and the process of redefining oneself.",
    tourStart: "2025-09-24",
    tourEnd: "2027-05-30"
  },
  {
    id: 15,
    featured: false,
    title: "ICÓNICA",
    artist: "Luana",
    country: ["uruguay"],
    type: "album",
    genre: "latin pop",
    status: "released",
    releaseDate: "2025-11-29",
    coverImage: "img/covers/iconica.jpg",
    artistImage: "img/artists/luana.jpg",
    tracks: ["ICÓNICA", "CUANDO SE BAILA LA PLENA", "TE BESO", "VOCÊ", "AMOR VERDADERO", "TU AURA", "FOCUSED", "SIENTO EL CALOR", "EL CAMINO", "DESPECHO"],
    totalTracks: 10,
    popularity: 55,
    spotifyUrl: "https://open.spotify.com/album/2LJDToWWCG1NbsIXQgwucJ",
    description: "A vibrant blend of Latin rhythms and contemporary pop that embraces confidence, self-expression, and individuality. Warm production and infectious energy drive songs that celebrate authenticity, empowerment, and the freedom to occupy space without apology.",
    tourStart: "2025-06-05",
    tourEnd: "2026-03-27"
  },
  {
    id: 16,
    featured: true,
    title: "Salud, Dinero y Amor",
    artist: "Davus",
    country: ["uruguay"],
    type: "album",
    genre: "alternative pop",
    status: "released",
    releaseDate: "2026-05-15",
    coverImage: "img/covers/salud-dinero-y-amor.jpg",
    artistImage: "img/artists/davus.jpg",
    tracks: ["Palabras Cruzadas", "Salud, Dinero y Amor", "Cada Vez", "Otra Vez", "Calíope (La Vida Es un Loop)", "Centinela", "Quién Te Viera", "Alejandro", "Niña Bonita (15)", "Tornasol", "Volverás", "Al Final"],
    totalTracks: 12,
    popularity: 46,
    spotifyUrl: "https://open.spotify.com/album/15Ne7MsXO16y0dyGCrRdiH",
    description: "An emotional journey that uses contemporary songwriting and alternative pop influences to reflect on the priorities that shape adult life. Through stories of relationships, expectations, setbacks, and personal growth, the project finds beauty and meaning even in moments of uncertainty while maintaining a warm and deeply human perspective.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 17,
    featured: false,
    title: "SUPERNOVA",
    artist: "Ralphie Choo",
    country: ["spain"],
    type: "album",
    genre: "experimental pop",
    status: "released",
    releaseDate: "2023-09-15",
    coverImage: "img/covers/supernova.jpg",
    artistImage: "img/artists/ralphie-choo.jpg",
    tracks: ["JUAN SALVADOR GAVIOTA", "NHF", "BULERÍAS DE UN CABALLO MALO", "TOTAL90NOSTALGIA", "BÓ", "WHIPCREAM", "WCID?", "GATA", "MÁQUINA CULONA", "VOYCONTODO", "SUPERNOVA", "TANGOS DE UNA MOTO TRUCADA", "BESO BRUMA", "METAVERSE"],
    totalTracks: 14,
    popularity: 70,
    spotifyUrl: "https://open.spotify.com/album/7KdsjQmMyF9B25UqADi117",
    description: "An unpredictable listening experience that refuses to fit neatly into a single genre. Flamenco, electronic music, experimental pop, and digital textures collide throughout the project, creating a constantly shifting landscape that explores identity, transformation, ambition, and the search for new forms of artistic expression.",
    tourStart: "2025-06-10",
    tourEnd: "2026-08-27"
  },
  {
    id: 18,
    featured: false,
    title: "petal",
    artist: "Ariana Grande",
    country: ["united states"],
    type: "album",
    genre: "pop",
    status: "coming",
    releaseDate: "2026-07-31",
    coverImage: "img/covers/petal.jpg",
    artistImage: "img/artists/ariana-grande.jpg",
    tracks: ["track 1", "hate that i made you love me", "track 3", "track 4", "track 5", "track 6", "track 7", "track 8", "track 9", "track 10", "track 11", "track 12"],
    totalTracks: 12,
    popularity: 70,
    spotifyUrl: "https://open.spotify.com/album/2k4FmEtXR0WiDW0Ac2QArT",
    description: "A collection of songs rooted in delicacy, introspection, and emotional honesty. Soft arrangements and elegant production create space for reflections on love, vulnerability, personal change, and the quiet moments that often define our lives. The project balances intimacy and sophistication while maintaining a strong emotional core.",
    tourStart: "2026-06-06",
    tourEnd: "2027-12-20"
  },
  {
    id: 19,
    featured: false,
    title: "Sweetener",
    artist: "Ariana Grande",
    country: ["united states"],
    type: "album",
    genre: "r&b",
    status: "released",
    releaseDate: "2018-08-17",
    coverImage: "img/covers/sweetener.jpg",
    artistImage: "img/artists/ariana-grande.jpg",
    tracks: ["raindrops (an angel cried)", "blazed (feat. Pharrell Williams)", "the light is coming (feat. Nicki Minaj)", "R.E.M", "God is a woman", "sweetener", "successful", "everytime", "breathin", "no tears left to cry", "borderline (feat. Missy Elliott)", "better off", "goodnight n go", "pete davidson", "get well soon"],
    totalTracks: 15,
    popularity: 90,
    spotifyUrl: "https://open.spotify.com/album/3tx8gQqWbGwqIGZHqDNrGe",
    description: "A bright and uplifting project that finds optimism even in difficult circumstances. Blending pop, R&B, and experimental elements, the album focuses on emotional recovery, resilience, gratitude, and the search for balance after periods of uncertainty. Its warm atmosphere makes it both reflective and empowering.",
    tourStart: "2026-06-06",
    tourEnd: "2027-12-20"
  },
  {
    id: 20,
    featured: true,
    title: "BRAT",
    artist: "Charli xcx",
    country: ["united kingdom", "india"],
    type: "album",
    genre: "hyperpop",
    status: "released",
    releaseDate: "2024-06-07",
    coverImage: "img/covers/brat.jpg",
    artistImage: "img/artists/charli-xcx.jpg",
    tracks: ["360", "Club classics", "Sympathy is a knife", "I might say something stupid", "Talk talk", "Von dutch", "Everything is romantic", "Rewind", "So I", "Girl, so confusing", "Apple", "B2b", "Mean girls", "I think about it all the time", "365"],
    totalTracks: 15,
    popularity: 96,
    spotifyUrl: "https://open.spotify.com/album/2lIZef4lzdvZkiiCzvPKj7",
    description: "A chaotic, energetic, and deeply self-aware collection of songs that transforms personal experiences into club-ready anthems. Packed with aggressive electronic production and brutally honest lyricism, it explores insecurity, ambition, friendship, fame, jealousy, and desire with a level of transparency rarely found in mainstream pop.",
    tourStart: "2026-06-03",
    tourEnd: "2027-08-10"
  },
  {
    id: 21,
    featured: false,
    title: "channel ORANGE",
    artist: "Frank Ocean",
    country: ["united states"],
    type: "album",
    genre: "r&b",
    status: "released",
    releaseDate: "2012-07-10",
    coverImage: "img/covers/channel-orange.jpg",
    artistImage: "img/artists/frank-ocean.jpg",
    tracks: ["Start", "Thinkin Bout You", "Fertilizer", "Sierra Leone", "Sweet Life", "Not Just Money", "Super Rich Kids", "Pilot Jones", "Crack Rock", "Pyramids", "Lost", "White", "Monks", "Bad Religion", "Pink Matter", "Forrest Gump", "End"],
    totalTracks: 17,
    popularity: 87,
    spotifyUrl: "https://open.spotify.com/album/392p3shh2jkxUxY2VHvlH8",
    description: "A cinematic blend of alternative R&B and soul that captures different stages of youth through vivid storytelling and memorable characters. The project explores love, identity, loneliness, privilege, desire, and social expectations while creating an immersive world filled with emotional depth and striking imagery.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 22,
    featured: true,
    title: "NO ME OLVIDES",
    artist: "Angela Torres",
    country: ["argentina"],
    type: "album",
    genre: "pop",
    status: "released",
    releaseDate: "2025-07-23",
    coverImage: "img/covers/no-me-olvides.jpg",
    artistImage: "img/artists/angela-torres.jpg",
    tracks: ["PLACARD", "OOPS!", "LUZ ROJA", "VERTIGO", "NO ME OLVIDES", "FAVORITA", "FRIKI", "DEMASIADO", "MAL", "SUPERHEROE", "DONDESTANMISAMIGOS"],
    totalTracks: 11,
    popularity: 58,
    spotifyUrl: "https://open.spotify.com/album/13cf0Quqq45QP6RVHhAhkT",
    description: "An emotionally charged project that moves between moments of confidence, vulnerability, and emotional chaos. Combining contemporary pop influences with introspective songwriting, it reflects on memory, self-worth, relationships, personal growth, and the fear of being forgotten by the people who matter most.",
    tourStart: "2026-12-09",
    tourEnd: "2027-02-18"
  },
  {
    id: 23,
    featured: true,
    title: "The Divine Feminine",
    artist: "Mac Miller",
    country: ["united states"],
    type: "album",
    genre: "alternative hip hop",
    status: "released",
    releaseDate: "2016-09-16",
    coverImage: "img/covers/the-divine-feminine.jpg",
    artistImage: "img/artists/mac-miller.jpg",
    tracks: ["Congratulations (feat. Bilal)", "Dang! (feat. Anderson .Paak)", "Stay", "Skin", "Cinderella (feat. Ty Dolla $ign)", "Planet God Damn (feat. Njomza)", "Soulmate", "We (feat. CeeLo Green)", "My Favorite Part", "God Is Fair, Sexy Nasty (feat. Kendrick Lamar)"],
    totalTracks: 10,
    popularity: 79,
    spotifyUrl: "https://open.spotify.com/album/6f6tko6NWoH00cyFOl4VYQ",
    description: "A romantic exploration shaped by influences from jazz, soul, and hip hop. Through lush arrangements and intimate storytelling, the project examines love, desire, admiration, intimacy, and emotional connection from multiple perspectives, creating a warm and deeply personal listening experience.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 24,
    featured: false,
    title: "Kiss All The Time. Disco, Occasionally.",
    artist: "Harry Styles",
    country: ["united kingdom", "england"],
    type: "album",
    genre: "disco pop",
    status: "released",
    releaseDate: "2026-03-06",
    coverImage: "img/covers/kiss-all-the-time-disco-occasionally.jpg",
    artistImage: "img/artists/harry-styles.jpg",
    tracks: ["Aperture", "American Girls", "Ready, Steady, Go!", "Are You Listening Yet?", "Taste Back", "The Waiting Game", "Season 2 Weight Loss", "Coming Up Roses", "Pop", "Dance No More", "Paint By Numbers", "Carla's Song"],
    totalTracks: 12,
    popularity: 86,
    spotifyUrl: "https://open.spotify.com/album/69BqE1V8Bzb9GCyeP1fFeR",
    description: "A project driven by creative freedom and the joyful spirit of disco-inspired pop. Balancing dancefloor energy with more introspective moments, it explores relationships, desire, escapism, and the pursuit of happiness through colorful production, infectious grooves, and a strong sense of personality.",
    tourStart: "2026-05-12",
    tourEnd: "2026-12-18"
  },
  {
    id: 25,
    featured: true,
    title: "Harry's House",
    artist: "Harry Styles",
    country: ["united kingdom", "england"],
    type: "album",
    genre: "soft rock",
    status: "released",
    releaseDate: "2022-05-20",
    coverImage: "img/covers/harrys-house.jpg",
    artistImage: "img/artists/harry-styles.jpg",
    tracks: ["Music For a Sushi Restaurant", "Late Night Talking", "Grapejuice", "As It Was", "Daylight", "Little Freak", "Matilda", "Cinema", "Daydreaming", "Keep Driving", "Satellite", "Boyfriends", "Love Of My Life"],
    totalTracks: 13,
    popularity: 93,
    spotifyUrl: "https://open.spotify.com/album/5r36AJ6VOJtp00oxSkBZ5h",
    description: "A warm and inviting collection of songs inspired by the beauty of everyday life. Gentle melodies, refined arrangements, and relaxed production create a space where themes of love, friendship, belonging, self-acceptance, and personal growth unfold naturally and without unnecessary dramatics.",
    tourStart: "2026-05-12",
    tourEnd: "2026-12-18"
  },
  {
    id: 26,
    featured: true,
    title: "Melodrama",
    artist: "Lorde",
    country: ["new zealand"],
    type: "album",
    genre: "art pop",
    status: "released",
    releaseDate: "2017-06-16",
    coverImage: "img/covers/melodrama.jpg",
    artistImage: "img/artists/lorde.jpg",
    tracks: ["Green Light", "Sober", "Homemade Dynamite", "The Louvre", "Liability", "Hard Feelings/Loveless", "Sober II (Melodrama)", "Writer In The Dark", "Supercut", "Liability (Reprise)", "Perfect Places"],
    totalTracks: 11,
    popularity: 88,
    spotifyUrl: "https://open.spotify.com/album/2B87zXm9bOWvAJdkJBTpzF",
    description: "An intense portrait of youth shaped by emotional extremes, unforgettable nights, and constantly evolving relationships. Combining ambitious pop production with deeply personal songwriting, the project explores heartbreak, loneliness, euphoria, self-discovery, and the search for meaning in moments that often feel overwhelming and transformative",
    tourStart: "2025-06-27",
    tourEnd: "2026-05-22"
  },
  {
    id: 27,
    featured: true,
    title: "HIT ME HARD AND SOFT",
    artist: "Billie Eilish",
    country: ["united states"],
    type: "album",
    genre: "alternative pop",
    status: "released",
    releaseDate: "2024-05-17",
    coverImage: "img/covers/hit-me-hard-and-soft.jpg",
    artistImage: "img/artists/billie-eilish.jpg",
    tracks: ["SKINNY", "LUNCH", "CHIHIRO", "BIRDS OF A FEATHER", "WILDFLOWER", "THE GREATEST", "L’AMOUR DE MA VIE", "THE DINER", "BITTERSUITE", "BLUE"],
    totalTracks: 10,
    popularity: 93,
    spotifyUrl: "https://open.spotify.com/album/7aJuG4TFXa2hmE4z1yxc3n",
    description: "A project that dives into the emotional contradictions and sudden shifts that define human relationships. Through dynamic production and intimate storytelling, it balances vulnerability and strength while exploring obsession, desire, loss, healing, and acceptance. Each song feels connected by a sense of emotional honesty and constant evolution.",
    tourStart: "2025-06-03",
    tourEnd: "2025-11-23"
  },
  {
    id: 28,
    featured: true,
    title: "KGB",
    artist: "ADÉLA",
    country: ["slovakia", "corea"],
    type: "single",
    genre: "electropop",
    status: "released",
    releaseDate: "2026-04-17",
    coverImage: "img/covers/kgb.jpg",
    artistImage: "img/artists/adela.jpg",
    tracks: ["KGB"],
    totalTracks: 1,
    popularity: 59,
    spotifyUrl: "https://open.spotify.com/album/06wdsqUb4GSuR29Luwiu8n",
    description: "A bold and futuristic pop track built around confidence, attitude, and striking electronic production. Its high-energy atmosphere and sharp aesthetic create a powerful statement about self-assurance, independence, and identity, while balancing sleek modern sounds with an unmistakable sense of personality.",
    tourStart: "2025-10-02",
    tourEnd: "2026-09-25"
  },
  {
    id: 29,
    featured: false,
    title: "PINKY UP",
    artist: "KATSEYE",
    country: ["united states", "china", "korea", "india", "switzerland", "philippines", "cuba"],
    type: "single",
    genre: "k-pop",
    status: "released",
    releaseDate: "2026-04-09",
    coverImage: "img/covers/pinky-up.jpg",
    artistImage: "img/artists/katseye.jpg",
    tracks: ["PINKY UP"],
    totalTracks: 1,
    popularity: 72,
    spotifyUrl: "https://open.spotify.com/album/5tLy0MEMDVqiHKso6B4jnz",
    description: "An energetic pop anthem driven by catchy melodies, infectious rhythms, and a confident attitude. Built around themes of empowerment, friendship, and self-expression, the song channels youthful energy through polished production and an upbeat atmosphere designed to feel both playful and empowering.",
    tourStart: "2025-06-21",
    tourEnd: "2026-12-25"
  },
  {
    id: 30,
    featured: false,
    title: "BAÑO MARÍA",
    artist: "CA7RIEL & Paco Amoroso",
    country: ["argentina"],
    type: "album",
    genre: "alternative hip hop",
    status: "released",
    releaseDate: "2024-04-17",
    coverImage: "img/covers/bano-maria.jpg",
    artistImage: "img/artists/ca7riel-paco-amoroso.jpg",
    tracks: ["BABY GANGSTA", "DUMBAI", "SHEESH", "MI DIOSA", "AGUA", "LA QUE PUEDE, PUEDE", "EL ÚNICO", "PIRLO", "VITAMINA", "COSAS RICAS", "SUPERSÓNICO", "DIABLO"],
    totalTracks: 12,
    popularity: 93,
    spotifyUrl: "https://open.spotify.com/album/1XX2taUAddEZQX4QinYxX2",
    description: "A genre-bending project that moves freely between hip hop, funk, electronic music, and Latin influences without losing its sense of identity. Humor, excess, desire, nightlife, and self-awareness coexist throughout the album, creating an experience that feels chaotic, entertaining, unpredictable, and surprisingly cohesive.",
    tourStart: "2026-06-1",
    tourEnd: "2026-12-15"
  },
  {
    id: 31,
    featured: false,
    title: "Barbie Copiloto",
    artist: "La Joaqui",
    country: ["argentina"],
    type: "EP",
    genre: "rkt",
    status: "released",
    releaseDate: "2022-12-01",
    coverImage: "img/covers/barbie-copiloto.jpg",
    artistImage: "img/artists/la-joaqui.jpg",
    tracks: ["38", "GD", "Butakera", "Dos Besitos", "Mañosa", "Traidora"],
    totalTracks: 6,
    popularity: 100,
    spotifyUrl: "https://open.spotify.com/album/1RTMX4nANYmn9nLTg1MTTy",
    description: "A confident and energetic project that combines urban sounds with playful storytelling and an unmistakable sense of attitude. Themes of independence, attraction, loyalty, and ambition appear throughout the songs, supported by production that balances intensity, charisma, and accessibility.",
    tourStart: "2025-06-20",
    tourEnd: "2026-04-24"
  },
  {
    id: 32,
    featured: false,
    title: "AMOR & DROGA",
    artist: "Tokischa",
    country: ["dominican republic"],
    type: "album",
    genre: "dembow",
    status: "released",
    releaseDate: "2026-04-16",
    coverImage: "img/covers/amor-droga.jpg",
    artistImage: "img/artists/tokischa.jpg",
    tracks: ["MI NOVIO", "SURFBOARD", "MONO (feat. KASE.O)", "CELOS", "VACIA", "PERREO LLORANDO", "BANDA", "7PM INTERLUDE", "DIVA Y DEPRESIVA", "HEROINA", "QUÉ ES EL AMOR?", "DROGA DE DISEÑADOR", "LOLA", "MIAMI", "MOTO", "SU FRIDA", "NANI"],
    totalTracks: 17,
    popularity: 69,
    spotifyUrl: "https://open.spotify.com/album/2nEcbAjssahw9l2VdiZswg",
    description: "A provocative exploration of desire, obsession, pleasure, and emotional dependency. Blending experimental reggaeton, electronic textures, and contemporary Latin influences, the project constantly shifts between vulnerability and empowerment while examining the different ways people seek connection, escape, and fulfillment.",
    tourStart: "2026-02-19",
    tourEnd: "2026-05-24"
  },
  {
    id: 33,
    featured: false,
    title: "GRASA",
    artist: "NATHY PELUSO",
    country: ["argentina", "spain"],
    type: "album",
    genre: "alternative hip hop",
    status: "released",
    releaseDate: "2024-05-24",
    coverImage: "img/covers/grasa.jpg",
    artistImage: "img/artists/nathy-peluso.jpg",
    tracks: ["CORLEONE", "APRENDER A AMAR", "REAL", "LEGENDARIO", "ESCALERAS DE METAL", "TODO ROTO", "NO LES CREO NADA - SKIT", "ENVIDIA", "MENINA", "IDEAS RADICALES", "MANHATTAN", "EL DÍA QUE PERDÍ MI JUVENTUD", "LA PRESA", "LA MENTIRA", "REMEDIO", "MAMÁ"],
    totalTracks: 16,
    popularity: 78,
    spotifyUrl: "https://open.spotify.com/album/2ab0PTJ5OG7I6YfSqpDFZv",
    description: "A deeply personal and ambitious project that reflects on fame, ambition, success, and the sacrifices that often accompany them. Drawing from rap, soul, salsa, and Latin music traditions, it combines sharp lyricism with cinematic production to create a complex portrait of identity and personal growth.",
    tourStart: "2025-06-12",
    tourEnd: "2026-05-30"
  },
  {
    id: 34,
    featured: false,
    title: "NO VAYAS A ATENDER CUANDO EL DEMONIO LLAMA",
    artist: "Lali",
    country: ["argentina"],
    type: "album",
    genre: "rock pop",
    status: "released",
    releaseDate: "2025-04-29",
    coverImage: "img/covers/no-vayas-a-atender-cuando-el-demonio-llama.jpg",
    artistImage: "img/artists/lali.jpg",
    tracks: ["POPSTAR", "LOKURA", "NO ME IMPORTA", "PLÁSTICO", "TU NOVIA II", "MORIR DE AMOR", "MEJOR QUE VOS", "NO HAY HÉROES", "SENSACIONAL ÉXITO", "PAYASO", "SEXY", "FANÁTICO", "PERDEDOR", "33", "PENDEJA", "FIN DE TRANSMISIÓN", "FANÁTICO (EN VIVO)"],
    totalTracks: 17,
    popularity: 79,
    spotifyUrl: "https://open.spotify.com/album/6I0pKnwFMnv4fC5KzEgPnq",
    description: "A dark and theatrical pop project that embraces intensity, rebellion, and emotional confrontation. Through powerful production, dramatic storytelling, and moments of vulnerability, it explores desire, obsession, ego, heartbreak, and self-destruction while maintaining a bold and unapologetic artistic vision.",
    tourStart: "2026-06-07",
    tourEnd: "2026-06-10"
  },

  {
    id: 35,
    featured: false,
    title: "ERIN BTR",
    artist: "erinbtr",
    country: ["uruguay", "ireland"],
    type: "EP",
    genre: "hyperpop",
    status: "released",
    releaseDate: "2026-01-10",
    coverImage: "img/covers/erin-btr.jpg",
    artistImage: "img/artists/erinbtr.jpg",
    tracks: ["DEFENSIVAHh", "CRASH OUT", "TFTK", "si tu novio es un pu$$y", "CHIkk!!!!"],
    totalTracks: 5,
    popularity: 10,
    spotifyUrl: "https://open.spotify.com/album/34uLP5SPREz6NZSlOeZsdw",
    description: "A bold and energetic EP that blends hyperpop, electronic production, and internet-age attitude into a chaotic yet cohesive listening experience. Distorted textures, explosive beats, and playful lyricism create a world where confidence, frustration, humor, and emotional vulnerability coexist. The project embraces digital culture while exploring identity, relationships, and self-expression through an unapologetically modern lens.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 36,
    featured: false,
    title: "redescubrir",
    artist: "anaclara",
    country: ["uruguay", "argentina"],
    type: "single",
    genre: "singer-songwriter",
    status: "released",
    releaseDate: "2026-02-05",
    coverImage: "img/covers/redescubrir.jpg",
    artistImage: "img/artists/anaclara.jpg",
    tracks: ["redescubrir"],
    totalTracks: 1,
    popularity: 12,
    spotifyUrl: "https://open.spotify.com/album/22fFKDXpUQOZLanQDt6a4G",
    description: "A reflective and emotionally driven song centered on growth, change, and the process of seeing familiar things from a new perspective. Gentle melodies and intimate songwriting create a warm atmosphere that explores self-discovery, healing, and the quiet moments that often lead to personal transformation.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 37,
    featured: false,
    title: "Por Tristán",
    artist: "Mauge Rodriguez",
    country: ["uruguay"],
    type: "single",
    genre: "singer-songwriter",
    status: "released",
    releaseDate: "2023-08-20",
    coverImage: "img/covers/por-tristan.jpg",
    artistImage: "img/artists/mauge-rodriguez.jpg",
    tracks: ["Por Tristán"],
    totalTracks: 1,
    popularity: 18,
    spotifyUrl: "https://open.spotify.com/album/4MFABqqFXJYdZTelZic5hF",
    description: "An intimate piece built around memory, affection, and emotional honesty. Through delicate instrumentation and heartfelt storytelling, the song reflects on the impact people leave on our lives, capturing both the beauty and the fragility of deeply personal connections.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 38,
    featured: false,
    title: "IMPOSTORA",
    artist: "Eugenia Anton",
    country: ["uruguay"],
    type: "EP",
    genre: "singer-songwriter",
    status: "released",
    releaseDate: "2025-10-24",
    coverImage: "img/covers/impostora.jpg",
    artistImage: "img/artists/eugenia-anton.jpg",
    tracks: ["Oh Maria!", "Pensar en no pensar", "Como fuego", "24/7", "Tic Tac", "Tiempo", "10 Pasos", "Bla"],
    totalTracks: 8,
    popularity: 20,
    spotifyUrl: "https://open.spotify.com/album/3nj1yIIszc9I8NMmAbHtAE",
    description: "A project that explores self-doubt, identity, and the pressure of living up to expectations through a blend of contemporary pop and emotionally charged songwriting. Moving between moments of vulnerability and empowerment, the songs examine insecurity, personal growth, and the struggle to find confidence in an increasingly demanding world.",
    tourStart: null,
    tourEnd: null
  },
  {
    id: 39,
    featured: false,
    title: "Luna Llena",
    artist: "Luana Mahia",
    country: ["uruguay"],
    type: "single",
    genre: "singer-songwriter",
    status: "released",
    releaseDate: "2025-10-03",
    coverImage: "img/covers/luna-llena.jpg",
    artistImage: "img/artists/luana-mahia.jpg",
    tracks: ["Luna Llena"],
    totalTracks: 1,
    popularity: 10,
    spotifyUrl: "https://open.spotify.com/album/0GqhbLOK3swfx0B7PGFxWU",
    description: "A dreamy and atmospheric song that uses the imagery of the moon to explore attraction, desire, and emotional intensity. Warm melodies, subtle rhythms, and an intimate vocal performance create a romantic atmosphere that feels both comforting and mysterious.",
    tourStart: null,
    tourEnd: null
  }
];